In [135]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from cvxopt import matrix 
from cvxopt import solvers
import time
from sklearn.metrics.pairwise import rbf_kernel, polynomial_kernel
from copy import copy
from sklearn.metrics import confusion_matrix
from scipy.stats import mode
from collections import defaultdict

In [57]:
def load_mnist(path, kind='train'):
    import os
    import gzip
    import numpy as np

    labels_path = os.path.join(path,
                               '%s-labels-idx1-ubyte.gz'
                               % kind)
    images_path = os.path.join(path,
                               '%s-images-idx3-ubyte.gz'
                               % kind)

    with gzip.open(labels_path, 'rb') as lbpath:
        labels = np.frombuffer(lbpath.read(), dtype=np.uint8,
                               offset=8)

    with gzip.open(images_path, 'rb') as imgpath:
        images = np.frombuffer(imgpath.read(), dtype=np.uint8,
                               offset=16).reshape(len(labels), 784)

    return images, labels



X_all_labels, y_all_labels = load_mnist('Data', kind='train')

indexLabel2 = np.where((y_all_labels==2))
xLabel2 =  X_all_labels[indexLabel2][:1000,:].astype('float64') 
yLabel2 = y_all_labels[indexLabel2][:1000].astype('float64') 

indexLabel4 = np.where((y_all_labels==4))
xLabel4 =  X_all_labels[indexLabel4][:1000,:].astype('float64') 
yLabel4 = y_all_labels[indexLabel4][:1000].astype('float64') 

indexLabel6 = np.where((y_all_labels==6))
xLabel6 =  X_all_labels[indexLabel6][:1000,:].astype('float64') 
yLabel6 = y_all_labels[indexLabel6][:1000].astype('float64') 

In [173]:
class Svm:
    
    def __init__(self, gamma, C, kernel):

        self.alpha = np.random.normal(0,1,(1,X.shape[0]))
        self.b = np.random.randint(1)
        self.C = C
        self.gamma = gamma
        self.kernel = kernel
        
    def predict(self,X):
        
        if self.kernel == "gauss":
            z = (self.alpha*self.y) @ self.kernel_gauss(self.X, X) + self.b
        if self.kernel == "poly":
            z = (self.alpha*self.y) @ self.kernel_poly(self.X, X) + self.b
        a = np.sign(z)    
        return a
        
    def kernel_gauss(self, X1, X2):
        return np.exp(-self.gamma*(np.sum(X1**2, axis = 1).reshape(-1,1) + np.sum(X2**2, axis = 1) - 2*np.dot(X1,X2.T)))
        
    def kernel_poly(self, X1, X2):
        return (X1 @ X2.T - 1)**self.gamma
    
    def compute_m_M(self, H, y):
        
        y = y.ravel(); C = self.C; alpha = self.alpha.ravel() 
        R = np.where((alpha < 1e-5) & (y == +1) | (alpha > C-1e-5) & (y == -1) | (alpha > 1e-5) & (alpha < C-1e-5))[0]
        S = np.where((alpha < 1e-5) & (y == -1) | (alpha > C-1e-5) & (y == +1) | (alpha > 1e-5) & (alpha < C-1e-5))[0]
        
        # negative gradient divided by y
        grad = H @ alpha - 1
        grady = - grad/y
        
        m = max(grady[R])
        M = min(grady[S])
        self.diff = m - M
        
    def fit(self, X, y):
        
        self.y = y
        self.X = X
        
        start = time.time()
        m = X.shape[0]
        y = y.reshape(-1,1)
        
        # computing alpha
        if self.kernel == "gauss":
            K = self.kernel_gauss(X, X)
        if self.kernel == "poly":
            K = self.kernel_poly(X, X)
        H = np.outer(y,y) * K
        P = matrix(H)
        q = matrix(-np.ones((m)))
        G = matrix(np.vstack((-np.eye(m),np.eye(m))))
        h = matrix(np.hstack((np.zeros(m), np.ones(m) * self.C)))
        A = matrix(y.reshape(1, -1))
        b = matrix(np.zeros(1))
                    
        #solvers.options['abstol'] = 1e-13
        solvers.options['feastol'] = 1e-15
        solvers.options['show_progress'] = False
        
        res = solvers.qp(P, q, G, h, A, b)
        alpha = np.array(res['x'])
        self.alpha = alpha.T
        
        time_elapsed = time.time() - start
        
        # computing b
        
        alpha = alpha.ravel()
        idx = np.where(alpha > 1e-5)[0]
        wy = ((y * alpha.reshape(-1,1)).T @ K[:,idx]).T
        b = y[idx] - wy
        self.b = np.mean(b)
        
        self.compute_m_M(H, y)
        
        return res["iterations"], time_elapsed
        
labels = [(1,2),(1,3),(2,3)]
permutations_x = [[xLabel2, xLabel4], [xLabel2, xLabel6], [xLabel4, xLabel6]]
permutations_y = [[yLabel2, yLabel4], [yLabel2, yLabel6], [yLabel4, yLabel6]]
hyperparameters = [(0.01,2,"gauss"), (0.1,1,"gauss"), (0.02,2,"gauss")]

y_all_train = []
y_all_test = []
votes_train = []
votes_test = []

iterations = 0
running_time = 0
for i in range(3):
    
    permutations_y[i][0][:] = +1
    permutations_y[i][1][:] = -1
    X = np.concatenate(permutations_x[i])
    y = np.concatenate([permutations_y[i][0], permutations_y[i][1]])

    X_train, X_test, y_train, y_test = train_test_split(X, y, stratify = y, test_size=0.2, random_state=1696995) 
    
    scaler = MinMaxScaler()
    X_train = scaler.fit_transform(X_train)
    X_test = scaler.fit_transform(X_test)
    
    comb = hyperparameters[i]
    
    svm = Svm(gamma = comb[0], C = comb[1], kernel = comb[2])
    its, time_elapsed = svm.fit(X_train, y_train)
    iterations += its
    running_time += time_elapsed
    
    y_pred = svm.predict(X_train)
    y_pred[y_pred == 1] = labels[i][0]
    y_pred[y_pred == -1] = labels[i][1]
    votes_train.append(y_pred)
    
    y_pred = svm.predict(X_test)
    y_pred[y_pred == 1] = labels[i][0]
    y_pred[y_pred == -1] = labels[i][1]
    votes_test.append(y_pred)
    
    y_train[y_train == 1] = labels[i][0]
    y_train[y_train == -1] = labels[i][1]
    y_all_train.append(y_train)
    
    y_test[y_test == 1] = labels[i][0]
    y_test[y_test == -1] = labels[i][1]
    y_all_test.append(y_test)

In [174]:
votes_train = np.array(votes_train).reshape(-1,1)
votes_test = np.array(votes_test).reshape(-1,1)
y_all_train = np.array(y_all_train).reshape(-1,1)
y_all_test = np.array(y_all_test).reshape(-1,1)

In [175]:
# predicted labels
majorities_test = mode(votes_test, axis = 0)[0].reshape(-1,1)
majorities_train = mode(votes_train, axis = 0)[0].reshape(-1,1)

In [176]:
print("- gamma_1 :", hyperparameters[0][0], "\t C_1 :", hyperparameters[0][1], "\t kernel_1 :", hyperparameters[0][2])
print("\n  gamma_2 :", hyperparameters[1][0], "\t C_2 :", hyperparameters[1][1], "\t kernel_2 :", hyperparameters[1][2])
print("\n  gamma_3 :", hyperparameters[2][0], "\t C_3 :", hyperparameters[2][1], "\t kernel_3 :", hyperparameters[2][2])
print("- accuracy on train :",np.mean(votes_train == y_all_train))
print("- accuracy on test :",np.mean(votes_test == y_all_test))
print("- confusion matrix :\n",confusion_matrix(y_all_test, votes_test))
print("- time elapsed :", time_elapsed)
print("- iterations :", its)
print("- m - M :", svm.diff)


- gamma_1 : 0.01 	 C_1 : 2 	 kernel_1 : gauss

  gamma_2 : 0.1 	 C_2 : 1 	 kernel_2 : gauss

  gamma_3 : 0.02 	 C_3 : 2 	 kernel_3 : gauss
- accuracy on train : 0.9685416666666666
- accuracy on test : 0.8808333333333334
- confusion matrix :
 [[351  15  34]
 [ 24 350  26]
 [ 24  20 356]]
- time elapsed : 17.953712701797485
- iterations : 100
- m - M : 3.108624468950438e-14
